language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

osx_image: xcode7.3
sudo: false
dist: trusty

env:
  global:
    - ERT_SHOW_BACKTRACE=1
  matrix:
    - TEST_SUITE="-LE SLOW"  # Run all tests not labeled as slow
    - TEST_SUITE="-L SLOW_1" # Run all tests labeled as SLOW in group 1
    - TEST_SUITE="-L SLOW_2" # Run all tests labeled as SLOW in group 2
    - TEST_SUITE=""          # TODO: Can be removed when libres is MacOS compliant

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang
    # TODO: The excludes below should be removed after MacOS is supported
    - os: linux
      env: TEST_SUITE=""
    - os: osx
      env: TEST_SUITE="-LE SLOW"
    - os: osx
      env: TEST_SUITE="-L SLOW_1"
    - os: osx
      env: TEST_SUITE="-L SLOW_2"


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - liblapack-dev
      - valgrind
      - gcc-4.8
      - g++-4.8
      - clang
      - cmake
      - cmake-data

install:
    - if [[ "$CC" == "gcc" ]]; then export CXX="g++-4.8"; fi
    - cmake --version
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export CONDA_OS=MacOSX;
      else
        export CONDA_OS=Linux;
      fi
    - export TRAVIS_PYTHON_VERSION="2.7"
    # We do this conditionally because it saves us some downloading if the version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-${CONDA_OS}-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-${CONDA_OS}-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export CONDA_HOME="$HOME/miniconda"
    - export PATH="$CONDA_HOME/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - conda install pyqt=4 scipy=0.16.1 pylint numpy pandas matplotlib future

before_script:
  - wget https://raw.githubusercontent.com/Statoil/ert/master/travis/build_total.py

script:
  - python build_total.py res ${TEST_SUITE}
